name: db_hooks

dependencies:
  - python=3.7.4
  - pip=19.2.3
  - appdirs=1.4.3
  - attrs=19.1.0
  - black=19.3b0
  - click=7.0
  - flake8=3.7.8
  - ipykernel=5.1.2
  - pandas=0.25.1
  - pygments=2.4.2
  - pyyaml=5.1.2
  - sqlalchemy=1.3.8
  - toml=0.10.0
  - twine=2.0.0
  - pip:
    - cachetools==3.1.1
    - cattrs==0.9.0
    - flake8-black==0.1.1
    - pip-tools==4.1.0
    - psycopg2-binary==2.8.3
