name: korbenware
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.6
  - pip=20.0.2
  - attrs=19.3.0
  - cattrs=1.0.0
  - click=7.1.1
  - crayons=0.3.0
  - flake8=3.7.9
  - ipykernel=5.1.4
  - marshmallow=3.5.0
  - pyee=7.0.1
  - pyflakes=2.1.1
  - pytest=5.4.1
  - pyxdg=0.26
  - toml=0.10.0
  - twisted=19.10.0
  - urwid=2.1.0
  - zope.interface=4.7.1
  - pip:
    - gshell.py==0.0.4
    - git+https://github.com/systemd/python-systemd.git#egg=systemd
    - twisted-ipython==2.0.0
    - txdbus==1.1.1
